version: '3'

services:

  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
     - /var/postgresql/data:/var/lib/postgresql/data
    ports:
     - "${POSTGRES_PORT}:5432"

  pgadmin4:
    image: dpage/pgadmin4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: "xxx@xxx.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
     - "80:80"
    depends_on:
     - db
    links:
      - db



      